### ISSUE TITLE
Summary table for catalog

### ISSUE THREAD

**Issue by jeromekelleher** [popgensims/manuscript#10]
Generate a LaTeX table summarising the contents of the catalog. If there is space, include some basic information about running a simulation [time/RAM] for the first chromosome for each model. The code for doing this would look a lot like the code for generating the [catalog](https://github.com/popgensims/stdpopsim/blob/master/docs/_ext/speciescatalog.py)

I'll have a quick go at this to see what's involved.

**Comment by jeromekelleher** [comment]
Related to #6, but less ambitious in terms of benchmarking.

**Comment by andrewkern** [comment]
thanks @jeromekelleher. i think those simulations could be quite minimal. say samples of size 2 from single population models or one sample from each population in multi-population models.

**Comment by andrewkern** [comment]
https://github.com/popgensims/manuscript/pull/14 closes this issue I believe
