### ISSUE TITLE
row name in params estimates figures 

### ISSUE THREAD

**Issue by agladstein** [popgensims/manuscript#102]
It looks like all of the figures of parameter estimates with multiple rows are missing the label for the first row.
Fig 2 (missing YRI label)
Fig 4 (missing YRI label)
Fig S1 (missing YRI label)
Fig S3 (missing Africa label)
Fig S4 (missing pop 1 label)

**Comment by ckyriazis** [comment]
so the label for the first row for all of these figs is in the parentheses following the species name.

**Comment by agladstein** [comment]
Oh, I see. Yeah, I didn't notice that. Probably okay to leave as is.
