### ISSUE TITLE
Results/catalog section

### ISSUE THREAD

**Issue by jeromekelleher** [popgensims/manuscript#103]
I was hoping to revamp the Results/catalog section but have run out of time. Here's what I was thinking:

- Change the name to "Species catalog" (having stdpopsim in section headers looks ugly IMO)
- Change the first paragraph to be a summary of what the catalog *is* not what it *contains*. It's a systematic organisation of key quantitative data needed to simulate a given species. 
- The next paras can then talk about table 1 and what's *in* the catalog. It would be nice to introduce the IDs for the models here, and then use the IDs subsequently (see #42)
-  Perhaps finish up with a para where we emphasise the point that we've put a lot of effort into making sure that stuff in the catalog will have long-term stable IDs. This is super important for reproducibility. Good note to finish the section on.

**Comment by andrewkern** [comment]
i'm working on a PR for this currently but would like to merge https://github.com/popsim-consortium/manuscript/pull/111 first
