### ISSUE TITLE
Remove pongo from paper

### ISSUE THREAD

**Issue by jeromekelleher** [popgensims/manuscript#104]
There's some difficulty about how we're handling Pongo in the software, and we don't want to paint ourselves into a corner by saying we've done it one way. See https://github.com/popsim-consortium/stdpopsim/issues/354

**Comment by andrewkern** [comment]
assigning myself this task. should be easy, but we should also remove it from Figure 1 @jradrion

**Comment by agladstein** [comment]
when we list models out in the text and in the table, then maybe we should say we are showing a subset of the available species/models (but we are continually adding more).

**Comment by andrewkern** [comment]
exactly

**Comment by jradrion** [comment]
>  we should also remove it from Figure 1 @jradrion


done

**Comment by andrewkern** [comment]
closing this as we should be set
