### ISSUE TITLE
link supplemental refs

### ISSUE THREAD

**Issue by agladstein** [popgensims/manuscript#109]
Once https://github.com/popsim-consortium/manuscript/issues/53 is resolved, it would be nice to have the supplemental refs linked correctly. I know that it can sometimes be tricky to figure out, depending on the document style.

**Comment by petrelharp** [comment]
They're linking correctly now!

**Comment by agladstein** [comment]
When I click S1 - S4 in the pdf, it links to Figure 1 - 4, not Figure S1 - S4.

**Comment by petrelharp** [comment]
Why so it does. I had tested with S5, which linked appropriately. I'll see what I can do.

**Comment by petrelharp** [comment]
OMG, finally figured it out: https://tex.stackexchange.com/questions/304814/hyperref-points-wrong-figure-table-with-reset-counter

**Comment by andrewkern** [comment]
ah the elegance of latex

**Comment by agladstein** [comment]
Good job. I know it's a pain.

**Comment by agladstein** [comment]
I verified. It works now
