### ISSUE TITLE
use logo from Fig1 as avatar for organization? 

### ISSUE THREAD

**Issue by andrewkern** [popgensims/manuscript#11]
what if we used the PopSim logo that @jradrion made for the github organization avatar?

**Comment by jeromekelleher** [comment]
Sure, let's try it out.

**Comment by jradrion** [comment]
Sounds good. Did people seem to like the stacked logo or the laptop better?

**Comment by andrewkern** [comment]
i tried the laptop first-- how's it look?

**Comment by jradrion** [comment]
It kinda squares-off the edges, so it looks a little weird in my opinion. Any chance we could see how the stacked one looks?

**Comment by jeromekelleher** [comment]
The laptop one looks kind of South Park at the moment, somehow. I can't decide if this is a good or bad thing.

**Comment by andrewkern** [comment]
hahaha okay let's see what the stacked one looks like

**Comment by andrewkern** [comment]
ugh the stacked one is too big. take a look. can we shrink it somehow?

**Comment by jradrion** [comment]
Sure, give me a sec.

**Comment by jradrion** [comment]
![logo_v6](https://user-images.githubusercontent.com/20053488/69662302-f43be380-1038-11ea-9a47-e98ba7d66c83.png)
OK, try this one.

**Comment by andrewkern** [comment]
almost.... it needs a bit more shrink... take a look

**Comment by jradrion** [comment]
Ahh, so close. One more second...

**Comment by jradrion** [comment]
![logo_v6](https://user-images.githubusercontent.com/20053488/69662976-3154a580-103a-11ea-8d6f-7f49239a20cc.png)
Hopefully this will do the trick.

**Comment by jeromekelleher** [comment]
Looks good!

**Comment by andrewkern** [comment]
looking really good now. closing this.
