### ISSUE TITLE
migration in model figures

### ISSUE THREAD

**Issue by agladstein** [popgensims/manuscript#110]
In the IM model figures, could they have multiple arrows to represent continuous migration, like in 4A? Otherwise, to me it looks like pulse geneflow, different from in A. Or am I misunderstanding and the migration in 4A and 4B are fundamentally different? I thought they are both continuous migration,

**Comment by ckyriazis** [comment]
you're correct that there is continuous migration - i'll add a few more arrows to the figures to help clarify that.

**Comment by andrewkern** [comment]
we good with this issue @agladstein?

**Comment by agladstein** [comment]
Looks good.
