### ISSUE TITLE
intro suggestion

### ISSUE THREAD

**Issue by asiepel** [popgensims/manuscript#117]
There are a couple of sentences at the end of the second paragraph of the intro where stdpopsim is introduced "Here we describe....", which strike me as awkward and evidently have bothered several others as well (based on a chain of comments in the *.tex file).  I think a big part of the problem is that this is just an odd place to introduce the resource -- in the second paragraph, in the middle of the general background for the resource.  My suggestion would be drop these sentences and save the introduction of the resource for the last paragraph in the intro.  The second paragraph might need to be reworked a bit to make the transition work.

I am raising this as an issue rather than just making the edits because it would require some restructuring, but I can take a shot at the edits if people agree it is worthwhile.

**Comment by andrewkern** [comment]
go for it Adam- sounds like it could be a very good edit.

**Comment by asiepel** [comment]
will do.

**Comment by klohmueller** [comment]
FWIW, Adam, I concur. Those few sentences about the resource seem out of place with the rest of the intro. Thanks for fixing!

**Comment by petrelharp** [comment]
This was done in b684ae5fb2da6bac8372f6dba4cd2c3da522d464
