### ISSUE TITLE
reconcile Results and Discussion regarding performance comparison

### ISSUE THREAD

**Issue by asiepel** [popgensims/manuscript#123]
I noticed some slight discrepancies between the Results section and Discussion section in summarizing the major outcomes of the performance comparison.  I'd like to take a shot at resolving these before we submit but can't do it right this minute.  Can do it first thing after lunch here (2ish EST)

**Comment by andrewkern** [comment]
@petrelharp is taking  a full pass through the manuscript right now, so be sure to update your version when you take a pass this afternoon

**Comment by andrewkern** [comment]
@asiepel I think we dealt with this so going to close. feel free to reopen if needed.
