### ISSUE TITLE
explanation of model codes

### ISSUE THREAD

**Issue by asiepel** [popgensims/manuscript#124]
Perhaps I missed something here but it looks like the number following the underscore in the model codes represents the number of populations in the simulation.  Can this be highlighted somewhere, e.g., in the legend of Table 1?  Or should it even be broken out as another column in the table?

**Comment by andrewkern** [comment]
I think we can point the reader to our documentation on naming conventions here: https://stdpopsim.readthedocs.io/en/latest/development.html#naming-conventions
