### ISSUE TITLE
Document how figures are produced

### ISSUE THREAD

**Issue by petrelharp** [popgensims/manuscript#125]
Not all figures have associated code - for instance, we should be able to find the code that produces Figure 4 by doing
```
grep homo_sapiens_two_popn_comp ** 2>/dev/null
```
in either this or the analysis repo. If the figure is made by hand, we should list somewhere (e.g., the README, or as a comment in the latex source) the constituent programatically generated sub-figures. Apologies if the info is there somewhere but I can't find it.

**Comment by ckyriazis** [comment]
So the code for this and other two pop figures is there but the file names were changed. I'll submit a PR to fix this.

**Comment by ckyriazis** [comment]
actually the real issue is that I made the cartoons in those figures by hand, and the file names changed going from the source code -> results panel -> final figures with cartoons. what do you suggest here @petrelharp?

**Comment by petrelharp** [comment]
Writing down in the README which code produced what figures. For instance:
```
The figure file homo_sapiens_two_popn_comp.pdf is a composite of the following figures: xyz.pdf, produced by the script abc.py in the analysis repository; ...
```

**Comment by petrelharp** [comment]
Just a simple pointer should do it - nothing detailed is necessary.

**Comment by ckyriazis** [comment]
ok see #131

**Comment by petrelharp** [comment]
thanks!
