### ISSUE TITLE
Include Arabidopsis results?

### ISSUE THREAD

**Issue by andrewkern** [popgensims/manuscript#130]
Folks the paper still doesn't include the 2 epoch AraTha result --- https://github.com/popsim-consortium/manuscript/blob/master/display_items/AraTha_African2Epoch_1H18.pdf

Should we stuff it in a little paragraph after the drosophila section in the results?

votes?

**Comment by ckyriazis** [comment]
i say yes! we have the results, might as well throw them in

**Comment by petrelharp** [comment]
Pros:
- includes a plant
Cons:
- we're almost @#(*$)) done, stop adding things.

I like adding a little paragraph. But this will also require at least a half-sentence in the Discussion, really. If you want, draft a PR with minimal changes?

**Comment by andrewkern** [comment]
closed by https://github.com/popsim-consortium/manuscript/pull/133
