### ISSUE TITLE
Capitalization of Stdpopsim

### ISSUE THREAD

**Issue by asiepel** [popgensims/manuscript#137]
The convention of capitalizing at the beginning of a sentence is not being uniformly applied

**Comment by andrewkern** [comment]
I've been trying to keep `stdpopsim` lowercase. Have you seen other examples?

**Comment by andrewkern** [comment]
oh sorry now I see the title of this Issue. Yes I've been changed that-- do you think it should be Uppercase?

**Comment by ckyriazis** [comment]
i think @jeromekelleher went through the ms yesterday and made it uppercase at the start of sentences

**Comment by asiepel** [comment]
someone added a \Stdpopsim command and applied it in some places.  I don't have a strong feeling either way but we should be consistent

**Comment by andrewkern** [comment]
Okay I will add back uppercase in my next pass through.

**Comment by jradrion** [comment]
@andrewkern I just changed the few instances where we used lowercase for starting a sentence. Please ignore the PR if we don't want to do this.

**Comment by andrewkern** [comment]
closed by https://github.com/popsim-consortium/manuscript/pull/139
