### ISSUE TITLE
Add response letter outline

### ISSUE THREAD

**Issue by jeromekelleher** [popgensims/manuscript#149]
As discussed in meeting 17/03, the response letter will be Markdown and will include the reviewer comments.

Add the initial stub for this, so that people who want to update the manuscript can also respond appropriately.

@andrewkern, I'm happy to take care of this, unless you want to?

**Comment by andrewkern** [comment]
looks like you got here already. closing.

**Comment by jeromekelleher** [comment]
Yep, sorry forgot to close the issue.
