### ISSUE TITLE
Citation style

### ISSUE THREAD

**Issue by jeromekelleher** [popgensims/manuscript#15]
What journal are we planning on submitting to, and what's their citation style? 

I find the current "double bracket" style a bit weird:

> implemented SLiM (Haller and Messer [2019])

I'm more familiar with either

>  implemented SLiM (Haller and Messer, 2019)

or 

>  implemented SLiM [numbered ref]

But, clearly following the house style for the journal is the best approach.

**Comment by andrewkern** [comment]
right so i figured we should import a nice template once we settle on a target journal. three ideas along those lines:

eLife
GENETICS 
G3

I think eLife and GENETICS are probably a stretch for this manuscript, where as G3 is a sure thing. eLife might want to take a chance on us though-- never know with that journal

**Comment by jeromekelleher** [comment]
SGTM. I'm very happy to let others decide the journal --- perhaps we should take this to email?

**Comment by andrewkern** [comment]
yeah- i'll start a new issue and email the group

**Comment by jeromekelleher** [comment]
Moved to Elife style in #41
