### ISSUE TITLE
Fig 1A api broken

### ISSUE THREAD

**Issue by agladstein** [popgensims/manuscript#153]
The example API code in Fig 1A isn't consistent with version 0.1.1.

It says `model = species.get_model("OutOfAfrica_3G09")`, but it should be `model = species.get_demographic_model("OutOfAfrica_3G09")`

**Comment by jeromekelleher** [comment]
Good spot @agladstein, things moved quickly at the end and this slipped through. I think you made this fig @jradrion?

**Comment by jradrion** [comment]
Yes, I will be updating this

**Comment by jradrion** [comment]
Actually, after looking at this again, it seems like the version of Figure 1 that made it on to bioRxiv and the elife submission is older than the version that has been uploaded to this repo since December 22. The newer version both corrected the above issue along with the following concern raised by Review 3, 

> I also tried the code in Figure 1B. Everything worked really well except that in Figure 1C the genetic map should be HapMapII_GRCh37 not HapmapII_GRCh37.

I'm having an issue with being able to complile the .tex file at the moment, can anyone confirm that it is still not being compiled with the updated Figure 1?

**Comment by jradrion** [comment]
OK, just recompiled and it is indeed being compiled with the updated/corrected version of Figure 1, however the issue with Figure 1C as raised by reviewer 3 was not actually corrected. I will upload a new version of the figure and close this issue.

**Comment by agladstein** [comment]
Yes, you are correct. Fig 1A is correct since 2459b37ba2e8bf0d9ed49bb2c663c5137894b738
and Fig 1C still needs to be corrected

**Comment by jradrion** [comment]
Actually, before I upload a revised figure, do we want to include API/CLI examples for both the msprime and SLiM engines now? 

@jeromekelleher @grahamgower Do you expect that any of the syntax will change in the near future? Updating this figure is pretty straightforward, and we can always leave this issue open and hold-off on updating the figure until things are finalized.

**Comment by grahamgower** [comment]
The interafaces shown here for CLI and API should be stable now, and barring any major unexpected problems they wont change in a backwards-incompatible way.

Probably it's not necessary to include examples for both slim and msprime. But IMO, it is worth changing from `get_default_engine()` to an explicit `get_engine("msprime")`, and adding `-e msprime` for the CLI. This hints strongly at how one would use a different engine, without having to waste space on actually giving another example.

**Comment by jradrion** [comment]
Excellent, thanks @grahamgower!

> But IMO, it is worth changing from get_default_engine() to an explicit get_engine("msprime"), and adding -e msprime for the CLI. This hints strongly at how one would use a different engine, without having to waste space on actually giving another example.

I agree, I think that should be sufficient.
