### ISSUE TITLE
convey uncertainty

### ISSUE THREAD

**Issue by petrelharp** [popgensims/manuscript#163]
Address various reviewer comments, e.g. the editor's:

> 1) Ensuring that the language about the models & parameters conveys the correct sense of uncertainty. Obviously the reviewers and the authors know that these just represent best guesses at the moment, but as this platform catches on we don't want these numbers & models to be seen as gospel. 

We need to put in a short paragraph making these caveats - probably early on? - and then make sure that detailed wording is appropriate, so that e.g. we refer to "published estimates" rather than "true values".  @ckyriazis said he'd take the first pass at this (but isn't showing up in the "assignees" for some reason?)

**Comment by ckyriazis** [comment]
starting work on this now, but have one quick question: in the response, is this a case where we should be quoting changes from the manuscript or would it be OK to just have a vague "we made the suggested change" response? the reason I ask is I'm making minor changes throughout, and it may be a pain to quote all of them individually.

**Comment by petrelharp** [comment]
No need to quote many minor changes, but it wouldn't be a bad idea to say "we did this throughough, for instance, we changed X to Y"; but we will also resubmit with a diff to the previous version, so we'll see themm.

**Comment by ckyriazis** [comment]
Took care of this in #171  - this can be closed
