### ISSUE TITLE
Remove supp figure from snakemake of two-pop workflow (S9)

### ISSUE THREAD

**Issue by petrelharp** [popgensims/manuscript#170]
A reviewer commented

> -Figure S9: unreadable when printed (not sure it adds a lot) 

and we decided that we might as well remove it. Feel free to argue otherwise.

**Comment by ckyriazis** [comment]
Taking care of this in my current round of edits, but I also noticed we dont actually reference Figure S8 (the DAG for the n_t analysis pipeline) anywhere in the manuscript either. Should we remove this as well?

**Comment by petrelharp** [comment]
I like it - I say refer to it somewhere?

**Comment by ckyriazis** [comment]
Ok I'll find a place to add it in.

**Comment by ckyriazis** [comment]
Took care of this in #171  - this can be closed
