### ISSUE TITLE
Add PapuansOutOfAfrica to the table

### ISSUE THREAD

**Issue by petrelharp** [popgensims/manuscript#172]
This one isn't in [Table 1](https://github.com/popsim-consortium/manuscript/blob/master/model_table.tex): https://stdpopsim.readthedocs.io/en/latest/catalog.html#sec_catalog_homsap_models_papuansoutofafrica_10j19 - who did the previous models, and can they do this one?
![Screenshot from 2020-04-17 10-41-28](https://user-images.githubusercontent.com/1046249/79597970-0544ca00-8098-11ea-91c8-e8c87ea1ed83.png)

**Comment by jeromekelleher** [comment]
That was probably me. I've assigned myself.
