### ISSUE TITLE
Response to reviewers

### ISSUE THREAD

**Issue by klohmueller** [popgensims/manuscript#175]
The response is looking awesome! Great work everyone!

Just a quick comment (that I thought would be easier to put here):

In terms of Reviewer 1, point 3 (on doing more SLiM stuff with a sweep), I think the response should also emphasize that PopSim is more of a software development/implementation project, rather than a research project.  We're making a resource we want people to use and are vouching for the QC of the models that we're including. As such, we think it's prudent to hold off simulating specific scenarios with selection as we don't have the bandwidth in time or space in the manuscript to give this important topic adequate attention. ie it's better to leave it out than doing a willy-nilly job on it.

Then we could mention the SLiM stuff that we did exploring the issue of scaling to show that SLiM can be included.

**Comment by jeromekelleher** [comment]
Can this be closed now?

**Comment by petrelharp** [comment]
@andrewkern should check on his pass?

**Comment by andrewkern** [comment]
closing this out now. think we've done a good job on justifying our revision.
