### ISSUE TITLE
citation update

### ISSUE THREAD

**Issue by jradrion** [popgensims/manuscript#180]
Some of our citations may be out-of-date. I'm happy to take a look and revise, but personally, I like waiting until right before submission to deal with these things, in order to avoid multiple changes. Perhaps, we should even wait until we hear back from the AE/reviews again, in case the timeline is unexpectedly delayed?

**Comment by jeromekelleher** [comment]
Looks like this is ready to go now @jradrion - are you happy to take this up?

**Comment by jradrion** [comment]
@jeromekelleher  sure, no problem!
