### ISSUE TITLE
Include Pongo species

### ISSUE THREAD

**Issue by apragsdale** [popgensims/manuscript#185]
The Pongo abelii species is also ready to be included in stdpopsim, including the genome build, two recombination maps, and one multi-population demographic model. It would be nice to have that reflected in the manuscript before the final version, and to say more than it's just "in development".

Unless someone thinks that would be a problem, I can go through the manuscript text and tables to include pongo while it's waiting to be merged into the catalog.

**Comment by petrelharp** [comment]
> The Pongo abelii species is also ready to be included in stdpopsim,

:yay!: :tada:!

> I can go through the manuscript text and tables to include pongo while it's waiting to be merged into the catalog.

Sounds good to me!!  Although this should probably be part of @jeromekelleher's assignment, #172, which also edits the tables? If not, waiting 'til the current round of edits blows over would be good.

**Comment by apragsdale** [comment]
Ok, sounds great! I'll hold off until this round of edits comes back.

**Comment by andrewkern** [comment]
awesome!

**Comment by jeromekelleher** [comment]
I'll take care of this once we've merged the various updates to stdpopsim.

**Comment by petrelharp** [comment]
Pongo has been merged, so I think this is on your plate now, @jeromekelleher?
