### ISSUE TITLE
Highlight error in OOA model in msprime docs?

### ISSUE THREAD

**Issue by jeromekelleher** [popgensims/manuscript#186]
Because I made a mistake in implementing the OOA model in the msprime docs, there's now quite a few published papers that use this flawed model. I think we should highlight this in the manuscript for several reasons:

1. It's a great argument for why we need stdpopsim
2. Our QC process caught the problem (thanks @apragsdale!!!)
3. It's a good way to highlight this problem in the literature and to warn people that there may be issues with conclusions drawn in these papers (seems unlikely, but it's possible).

Linked issues: 

https://github.com/tskit-dev/msprime/issues/981
https://github.com/popsim-consortium/stdpopsim/pull/496

**Comment by petrelharp** [comment]
Sounds good -  how about this?
```
The possibility for error and the importance of careful qualty control
was inadvertantly illustrated during our own development process:
during the final revisions of this paper, we noticed that the \citet{gutenkunst} model
had not in fact gone through the QC process.
Then, the QC process revealed that not only was our implementation slightly wrong --
migration rates had not been set to zero to the European population in the longest-ago time period
when there should have been only a African population.
This error was in fact propagated from the \msprime documentation.
```

**Comment by petrelharp** [comment]
Inserted [here](https://github.com/popsim-consortium/manuscript/blob/8229ba9549c46f8209651638c61c9a9173931783/popSimManu.tex#L836)?

**Comment by petrelharp** [comment]
To make the point more forcefully we could cite some of the papers that have used the wrong implementation from the msprime docs...

**Comment by jeromekelleher** [comment]
> To make the point more forcefully we could cite some of the papers that have used the wrong implementation from the msprime docs...

I'll do a bit of digging - I know a few off the top of my head anyway.

**Comment by jeromekelleher** [comment]
The text looks good, thanks @petrelharp.

**Comment by petrelharp** [comment]
Maybe we don't want to call out anyone else's papers explicitly actually, might be a bit rude...

**Comment by petrelharp** [comment]
Unless it's one of our own?

**Comment by jeromekelleher** [comment]
A quick search of GitHub suggests it's been copied into ~30 repos, e.g.
 
https://github.com/search?q="T_AF+%3D+220e3+%2F+generation_time"&type=Code

https://github.com/search?q=out_of_africa+msprime&type=Code

I've spotted a good few of these which are definitely papers now. I think I'll have to follow up with everyone I can track down to try to let them know. What a mess.
