### ISSUE TITLE
species vs genera vs taxa

### ISSUE THREAD

**Issue by sgravel** [popgensims/manuscript#189]
We refer to "species" in the manuscript to refer to both species and genera (pongo and drosophila). I'd suggest using taxa. Putting this as an issue to since people might not read the edits at this point.

**Comment by sgravel** [comment]
Actually, this can be fixed while minimizing rewrite and verbosity by simply clarifying: 

> The package centers on a catalog of species (and broader taxa) ...

**Comment by petrelharp** [comment]
Oh, good call.
