### ISSUE TITLE
target journal

### ISSUE THREAD

**Issue by andrewkern** [popgensims/manuscript#19]
@jeromekelleher and i started discussing possible target journals for the manuscript over on https://github.com/popgensims/manuscript/issues/15 and wanted to start a broader discussion.

Where to folks want to submit? Some journals that makes sense to me would be eLife, GENETICS, or G3

**Comment by jeromekelleher** [comment]
Pinging @popgensims/all for input on this.

**Comment by reedacartwright** [comment]
eLife sounds like a good place to start.

**Comment by klohmueller** [comment]
I think we had been thinking about Genome Biology. I know we missed the deadline on the special issue, but I still think this would be a great fit!

I'm not sure Elife publishes anything with models...

**Comment by andrewkern** [comment]
so wrt to eLife-- i don't think they've ever published something like this before but with Eisen as the EIC i'd be keen to see if they would. this paper will be impactful if not glamorous.

**Comment by dschride** [comment]
Proposed ladder: 1. eLife, 2. Genome Biology, 3. GENETICS

**Comment by gtsambos** [comment]
I'd prefer this article to be open-access if possible. Otherwise no strong feelings

**Comment by jeromekelleher** [comment]
Closing as we've converged on eLife.
