### ISSUE TITLE
Figure 1 proposal

### ISSUE THREAD

**Issue by jeromekelleher** [popgensims/manuscript#2]
Here's a (very!) rough first pass at an illustrative figure 1. The idea is to have a number of panels showing different aspects of the software:

a. Show the catalogue in a tree-like way. We want to emphasise that we're gathering together all the important information that we'd need to run simulations of a species in one place.
b. Show that cloud resources with a transparent cache are used for large stuff like genetic maps.
c. Snippets showing the Python API and CLI in action (maybe this should be panel B, since we use the CLI in the current B?)
d. I was thinking of putting in an illustration of the QC process, where Ann proposes a model implementation and Bob makes a blind implementation and we check if they are identical. I can't draw well enough to do this though! 

These would be four key things to get across about the software though.

Thoughts? (Other than about how terrible my writing is!)

![stdpopsim-fig](https://user-images.githubusercontent.com/2664569/68234570-6a7c9580-fff9-11e9-8a40-d11cc0b6f057.jpg)

**Comment by petrelharp** [comment]
I like it. What'd be a good example CLI snippet? If this could be closer to
a quickreference, somehow, rather than just a single example, I think that
would help.

**Comment by andrewkern** [comment]
I like this too Jerome. Want to tag @jradrion here to make sure he sees too.

**Comment by jradrion** [comment]
I like it too. The only think I'm lukewarm on including is example API/CLI code, only because I imagine that we will want a full example pipeline available on the repo for install testing purposes. That being said, it could work here as well.

**Comment by jeromekelleher** [comment]
Great, glad you all like the basic idea. This is just a rough idea of somewhere to start --- let's see how it works out. Totally open to dropping the code snippets entirely.

**Comment by petrelharp** [comment]
As you see fit, but I'm voting for *more* example API/CLI code, not less, because the more concretely we can show people how easy it is to use this, the better.

**Comment by jeromekelleher** [comment]
> As you see fit, but I'm voting for more example API/CLI code, not less, because the more concretely we can show people how easy it is to use this, the better.

Good point.

**Comment by klohmueller** [comment]
I like this too! Do we want to have any sort of output shown in panel D? Do we want to include anything in terms of the analysis side? Or should we keep that as a separate figure because it's not a direct part of the resource? Thoughts?

**Comment by jeromekelleher** [comment]
> Do we want to have any sort of output shown in panel D?

Good idea: It might be nice to show that the output is a tskit tree sequence file. Perhaps we could work the tskit logo in here somehow??

>  Do we want to include anything in terms of the analysis side? Or should we keep that as a separate figure because it's not a direct part of the resource? Thoughts?

I think we probably don't need a figure for the analysis side. In my mind, the analysis repo is more  "the code we used to generate the figures is on GitHub: please feel free to adapt it for your own needs" rather than "the analysis repo is production ready software that you should use in your analyses". I think it would be a **lot** of work to make the analysis code sufficiently general, tidy and hardened to justify the latter.

**Comment by jradrion** [comment]
I'm feeling pretty good about this, but I welcome any suggestions.
![Figure1_v3](https://user-images.githubusercontent.com/20053488/69199243-425a5f80-0aec-11ea-9c24-ef876ea7a3f9.png)

**Comment by petrelharp** [comment]
Looks very nice!  Minor comment: you can omit the `\` and `>` in the CLI, I think?

**Comment by jeromekelleher** [comment]
Looks great! Some minor comments:

- In (C) we don't need the msprime import
- We should remove the ``length_multiplier=0.01`` parameter from ``get_contig`` as it can't be used with the ``genetic_map`` argument.)
- Replace line 8 with ``model = species.get_model("ooa_2")``. (The model classes are an implementation detail that are hidden away from the users; gives us more freedom on how we arrange things in the future).
- I wonder if (B) would be a bit clearer if we used a standard flowchart type layout for the "does local cache exist"? Also, I'm not sure what decision occurs at ``msprime.read_hapmap`` --- this either succeeds or fails with an error, I think.
- For (A), is it more usual to use a sideways triangle to indicate an open tree node than upside-down?

**Comment by jradrion** [comment]
@petrelharp ,@jeromekelleher
Thank you both for your comments! I will post an update with your suggestions some time soon.

**Comment by jeromekelleher** [comment]
An update here @jradrion --- we need to change the code slightly after @grahamgower's addition of the simulation engine api. We'll want to add
```python
engine = stdpopsim.get_engine("msprime") # Or maybe get_default_engine()? I'm not sure
...
engine.simulate(model, contig, samples)
```

**Comment by andrewkern** [comment]
@jradrion hoping you could push the current figure to the repo as a PR. version on the repo is dated already

**Comment by jradrion** [comment]
@andrewkern done, though I still need to work on incorporating @jeromekelleher's comments. I'll continue with the PRs as I make more substantial updates.

**Comment by jradrion** [comment]
![Figure1_v5](https://user-images.githubusercontent.com/20053488/69989371-53e23500-14f8-11ea-82f4-6243192abe61.png)

I went with macOS-style node triangles, where right-pointed triangles indicate closed folders and downward-pointed triangles indicate expanded folders. I'm still somewhat unconvinced of the value added by panels B and D, though I'm fine with keeping them as is for now. I'm also willing to change them if anyone would like to sketch out a different design.

**Comment by jeromekelleher** [comment]
Looks great. I'm also less convinced that B and D add much. Perhaps we should just drop B anyway --- this concept can probably  be communicated more effectively in the text.

**Comment by andrewkern** [comment]
i agree B doesn't add much, but currently it does carry some weight in the way that I refer to Fig1B from the text. Have you had a read through yet @jeromekelleher?

**Comment by jeromekelleher** [comment]
> i agree B doesn't add much, but currently it does carry some weight in the way that I refer to Fig1B from the text. Have you had a read through yet @jeromekelleher?

No, haven't had a proper pass through. Will do ASAP.

**Comment by andrewkern** [comment]
closing this but we can reopen if people want to hash out figure 1 more later

**Comment by jeromekelleher** [comment]
Reopening this as I think B and D should be removed. After #99, there are no references to these in the text. I think they will only confuse people, and the space would be better used on making (C) bigger.

**Comment by jeromekelleher** [comment]
Also, will need to update the figure to change "HapmapII_GRCh37" to "HapmMapII_GRCh37"

**Comment by andrewkern** [comment]
let's ping our own Michelangelo @jradrion 

and while we are at it-- what about the Pongo name for the figure?

**Comment by andrewkern** [comment]
I vote we go with abelii throughout-- we can easily change the internals on stdpopsim with a few find/replace

**Comment by jeromekelleher** [comment]
Has to be PonPyg, that's what we have in the Catalog.

**Comment by jeromekelleher** [comment]
Or leave Pongo out of the manuscript entirely, it's pretty vestigial.

**Comment by andrewkern** [comment]
I think we should keep it in and just make sure everything says Pongo pygmaeus in the paper

**Comment by jeromekelleher** [comment]
Sure, happy to keep it in as PonPyg

https://stdpopsim.readthedocs.io/en/latest/catalog.html#sec_catalog_PonPyg

This is what we've released, I think we need to stick with that now. We'll fix the bugs in the genome info.

**Comment by jradrion** [comment]
@jeromekelleher @andrewkern I'll work on these updates

**Comment by jradrion** [comment]
![Figure1_v8b](https://user-images.githubusercontent.com/20053488/71206704-071d8e80-225a-11ea-8b83-a15381db17c7.png)
We could do something like this if we remove _E. coli_, which at this time isn't found in Table 1 either. I could scrap _Pongo_ too?
Thoughts?

**Comment by andrewkern** [comment]
yes let's scrap pongo

**Comment by jradrion** [comment]
![Figure1_v8d](https://user-images.githubusercontent.com/20053488/71209209-bf016a80-225f-11ea-8591-63841a0f09c5.png)
I'll go ahead and replace the current Fig 1 if everyone is satisfied with this version?

**Comment by andrewkern** [comment]
this looks good Jeff. Can you submit a PR for this and please massage the associated text?

**Comment by andrewkern** [comment]
closed by https://github.com/popsim-consortium/manuscript/pull/108
