### ISSUE TITLE
issues raised by Ilan

### ISSUE THREAD

**Issue by andrewkern** [popgensims/manuscript#203]
Ilan sent me the following email. Sharing it here on the TODO list:

>Andy,
>
>A couple of minor things I found in a final read of the manuscript:
>1) page 5, line 132: I'd suggest merging the two intro paragraphs to the results into one >paragraph. Also, "simulation model descriptions" reads a bit awkward. Maybe replace with >something simpler like "demographic models" (even if it doesn't capture everything).
>2) page 15, line 392: Figures 3 & S6--> Figures 3 and S6.
>
>Also, I'd be happy to suggest a modified statement describing fig S2 after the fig has been >finalized. I can get to that tomorrow am.
>
>--Ilan

**Comment by gphocs-dev** [comment]
A few more minor issues in the response letter:

1. Page 2, in the beginning of the 2nd paragraph "an a section"
2. Page 8, first response paragraph should cite Supp fig S3 and not S1.

**Comment by petrelharp** [comment]
Thanks! Fixed these; sufficiently minor that I didn't do a PR.
