### ISSUE TITLE
Resubmission

### ISSUE THREAD

**Issue by andrewkern** [popgensims/manuscript#206]
All issues are closed; manuscript is ready to go out the door. 

I'm going to go ahead and resubmit unless I hear objections in the next few hours.

**Comment by andrewkern** [comment]
ugh our abstract is now over the word limit. I've taken the liberty of editing it down to this:

> The explosion in population genomic data demands ever more complex modes of analysis, and increasingly these analyses depend on sophisticated simulations. Recent advances in population genetic simulation have made it possible to simulate large and complex models, but specifying such models for a particular simulation engine remains a difficult and error-prone task. Computational genetics researchers currently re-implement simulation models independently, leading to inconsistency and duplication of effort. This situation presents a barrier to researchers seeking to use simulations for power analyses or sanity checks on existing genomic data.
> Here we describe a new resource, stdpopsim, that rectifies this situation. Stdpopsim is a community-driven open source project, which provides easy access to a catalog of published simulation models from a range of organisms. We share examples demonstrating how stdpopsim
> can be used to compare demographic inference methods, and we encourage a broader
> community of developers to contribute to this growing resource.

**Comment by andrewkern** [comment]
open to suggestions from folks that might be awake and working on a Saturday AM

**Comment by andrewkern** [comment]
done! 🎊

**Comment by petrelharp** [comment]
Thanks, Andy!
