### ISSUE TITLE
eLife requesting formatting changes

### ISSUE THREAD

**Issue by andrewkern** [popgensims/manuscript#207]
This is a pain in the ass.... see below

---------

Dear Andrew,

Thank you for sending the revised version of your work for consideration at eLife. We have checked your submission and we would like to ask you to address the following points before we proceed:

*We have noticed that you have submitted a single manuscript file in the same format as your initial/full submission. At revised submission, however, we ask that authors instead upload an editable file (e.g., a Word document or LaTeX file) as an Article File. For .tex files, please ensure all .cls, .sty, and .bib files are uploaded along with a clean, compiled PDF. 

Figures and figure supplements should be uploaded as separate, individual files (e.g., as figure files or figure supplements). Full details can be found on our Author Guide: http://submit.elifesciences.org/html/elife_author_instructions.html

*We would like you to change the way in which the supplementary figures included with your submission are cited. Each figure supplement should be associated with a main figure. Please order them and cite them sequentially, e.g., Figure 1, Figure 2, Figure 2-figure supplement 1, Figure 2-figure supplement 2, Figure 3, Figure 3-figure supplement 1, and so on) and ensure any references to these figures in your response to the review comments are also updated. 

Here are some examples of figure supplements in a published article to illustrate how we handle these: https://elifesciences.org/articles/03222/figures#fig2s1 and https://elifesciences.org/articles/03222/figures#fig2s2

*Please could you upload a completed transparent reporting form alongside your paper. You can download a copy of the form as a PDF or a Word file here:

[https://elife-cdn.s3.amazonaws.com/xpub/guides/transparent_reporting.pdf]

[https://elife-cdn.s3.amazonaws.com/xpub/guides/transparent_reporting.docx]

Please note that we will publish the completed Transparent Reporting Form for submissions accepted for publication. This will be available to download as a supplementary file in the format provided by the authors.

*Impact statements for eLife research articles should be written in third-person and cannot use phrases like: "We", "I", "Our", "This study", "This work", or any similar phrase. Please rephrase your impact statement so that it either just clearly states the main finding, or uses more descriptive phrases that provide new information: "Genetic analyses reveal..." or "A biochemical approach shows...". Please also bear the following guidance in mind when rewriting your impact statement:

Impact statements for eLife research articles must be a single and complete sentence (i.e. not multiple sentences or a fragment).
They need to complement (rather than repeat) the title of the article.
Good impact statements are also short (i.e. < 30 words) and use as few unfamiliar acronyms as possible.

<EXAMPLES>
Instead of... 
"We reveal mechanisms by which protein compartments assemble around enzymes and reagents to facilitate reactions in bacteria."
Try...
"Computational and theoretical models reveal how protein compartments assemble around enzymes and reagents to aid reactions in bacteria."

Rather than...
"This paper shows that the molecular target of a natural product with promising anticancer activity is a membrane phospholipid."
Use...
"An unbiased genetic screen in human cells shows that the molecular target of a natural product with promising anticancer activity is a membrane phospholipid."

* Please note that we will publish the eLife Transparent Reporting Form for submissions accepted for publication.

* We would encourage you to include a Key Resources Table within your article file, at the start of the Materials and Methods, if your paper involves bench research. This is designed to highlight genetically modified organisms and strains, cell lines, reagents, and software that are essential to reproduce the results presented, but it is not designed to be a comprehensive list of all the materials and resources used. If you would like to include one, please download the following template, https://elife-cdn.s3.amazonaws.com/author-guide/elifeKRTtemplatev2.docx, complete it, and then incorporate the Key Resources Table within the article file (examples in published articles are available at https://elifesciences.org/articles/32586#s4 and https://elifesciences.org/articles/31023#s4). 

* To help promote the identification, discovery, and reuse of key research resources, we encourage you to include Research Resource Identifiers (RRIDs) within the Materials and Methods section (and/or Key Resources Table) to identify model organisms, cells lines, antibodies, and tools (such as software or databases) you have used (e.g. RRID:AB_2178887 for an antibody, RRID:MGI:3840442 for an organism, RRID:CVCL_1H60 for a cell line, and RRID:SCR_007358 for a tool). The RRID Portal (https://scicrunch.org/resources) lists existing RRIDs, and instructions for creating a new one if an RRID matching the resource does not already exist.

* If you haven't already, we also strongly encourage you to upload relevant additional data files, such as numerical data that are represented as a graph in a figure, or as a summary table. Where provided, these should be in the most useful format, and they can be uploaded as "Source data" files linked to main figures and/or tables (e.g., Figure 1-source data 1, Table 1-source data 1).

You will find your article marked as "Awaiting Author Approval" on the Author Tasks screen, which you can access via the following link: 

[https://submit.elifesciences.org/cgi-bin/main.plex?el=A3Hz1bjC1B3tyh5F5A9ftdDfeVK3OWkgwHPhXm32YztQZ]

Please make the changes specified above and then submit your paper following the same steps as before. We look forward to checking your files again in the near future, but please let us know if you have any questions. 

Best wishes, 

Tara

Tara Bristow
eLife editorial support
editorial@elifesciences.org

eLife Sciences Publications, Ltd is a limited liability non-profit non-stock corporation incorporated in the State of Delaware, USA, with company number 5030732, and is registered in the UK with company number FC030576 and branch number BR015634 at the address Westbrook Centre, Milton Road, Cambridge, CB4 1YG, UK.

**Comment by petrelharp** [comment]
I say we write back and say that we disagree with this requirement that every supp fig has a main figure? People should be encouraged to include sanity check and descriptive figures as supplements that don't need to be included in the main text; this will make that hard.  Seems like it goes against the sort of transparency that eLife is supposed to represent.

**Comment by jeromekelleher** [comment]
Yeah, I agree. This seems like a pretty stupid requirement for a paper like this.

**Comment by andrewkern** [comment]
i also agree. i'll send a note and push back, along with the files they request

**Comment by jeromekelleher** [comment]
Thanks Andy!

**Comment by petrelharp** [comment]
If we want to make it carry more weight, we could get the co-authors to explicitly sign on.

**Comment by andrewkern** [comment]
i sent a DM to the EiC.... will report back what I'm told

**Comment by andrewkern** [comment]
okay had convo with EiC. He approved of our plan to push back.
