### ISSUE TITLE
Methods: popsim structure

### ISSUE THREAD

**Issue by andrewkern** [popgensims/manuscript#28]
hey @jeromekelleher can you write a paragraph or two here  describing the implementation:

https://github.com/popgensims/manuscript/blob/94e3838215a1a3c1e8beaf867724079597429fb4/popSimManu.tex#L463

**Comment by jeromekelleher** [comment]
Will do. It'll be early next week though.

**Comment by jeromekelleher** [comment]
I've made a few attempts at writing this, but it ends up saying the same thing as what we have in the "Results" section differently.  What sort of stuff do you imagine going in here @andrewkern, and perhaps we could just elaborate on these in the Results section? The distinction between "results" and "methods" seems a bit meaningless to me when they're both talking about some software.

**Comment by andrewkern** [comment]
i think what's in this commit looks good @jeromekelleher. it's alright if we are redundant in the methods IMHO. Do you want to submit a PR with this?

**Comment by jeromekelleher** [comment]
OK, I'll make a pass through it once stdpopsim is shipped.

**Comment by jeromekelleher** [comment]
I've added all the details I think are needed to the results section in #99. I don't think we need a section in the methods, so going to close.
