### ISSUE TITLE
Methods: QC section edit

### ISSUE THREAD

**Issue by andrewkern** [popgensims/manuscript#29]
@ndukler can you take a pass on the QC section that I wrote here? 

https://github.com/popgensims/manuscript/blob/94e3838215a1a3c1e8beaf867724079597429fb4/popSimManu.tex#L465

**Comment by ndukler** [comment]
This looks pretty good except for a tiny revision to this sentence "Imagine Developer A
wants to introduce a new model into stdpopsim. Developer A implements the
demographic model for the relevant organism along with ~~a series of required
unit tests and~~ clear documentation of the model parameters and populations." Developer A should never need to add unit tests to my knowledge and I never have.

**Comment by ndukler** [comment]
@andrewkern do you want me to make the edit myself or would you prefer to do it?

**Comment by jeromekelleher** [comment]
Just go for the edit @ndukler and open a PR I'd say.

**Comment by ndukler** [comment]
Okay
