### ISSUE TITLE
analysis results on generic models

### ISSUE THREAD

**Issue by ckyriazis** [popgensims/manuscript#37]
One topic I meant to bring up on our call this week is to what extent we want to include analysis results on the generic models. My opinion is that these results were pretty informative (e.g., seeing that MSMC still infers the same squiggle on a constant population size model) and should be included in the supplement and briefly referred to in text. For the two population pipeline, I think showing the results on the generic IM model are also useful from the perspective of ground truthing the inference in a case where the model is correctly specified. 

What do others think?

**Comment by andrewkern** [comment]
yeah this is a good issue to bring up. I agree it would be worth doing one or two of these and stuffing results in the supplement.

**Comment by RyanGutenkunst** [comment]
Agreed. Definitely should put some in.

**Comment by ckyriazis** [comment]
FWIW, here are the generic IM results. I can add this and the plotting code to the ms repo. 
![image](https://user-images.githubusercontent.com/11757173/70659405-e67b8600-1c14-11ea-996e-68b492d86e96.png)

**Comment by andrewkern** [comment]
these look great @ckyriazis. can you submit them to the repo with a PR?

**Comment by ckyriazis** [comment]
sure will do.

**Comment by ckyriazis** [comment]
closing this
