### ISSUE TITLE
popsim logo ideas?

### ISSUE THREAD

**Issue by andrewkern** [popgensims/manuscript#4]
two ideas for a popsim logo:

1) we are sort of creating a factory (a standardized production facility) for tree sequences. Maybe we could have a factory thing going on?

2) riffing off of @jradrion's idea of the popsim logo sitting above the tskit logo-- maybe the popsim project is like a forest that has all these different sorts of tree sequences within it?

**Comment by jradrion** [comment]
![logo_v1](https://user-images.githubusercontent.com/20053488/68703134-d5b8f100-053e-11ea-805f-6ad5f7e31d3e.png)
This was my idea.

**Comment by jeromekelleher** [comment]
Or, a variant on your catalog idea @jradrion?

**Comment by jradrion** [comment]
I like the idea of a factory though...maybe with tree sequences coming out of the smoke stacks?

**Comment by andrewkern** [comment]
Yes!

**Comment by jradrion** [comment]
![logo_v3](https://user-images.githubusercontent.com/20053488/68711983-a363bf80-054f-11ea-9f80-081013f56c5f.png)

Here's a quick compromise that doesn't involve me attempting to draw a factory.

**Comment by petrelharp** [comment]
Very nice. Here's another one: clouds, raining down trees?
![logo_v4 pdf](https://user-images.githubusercontent.com/1046249/68732476-65cf5880-0588-11ea-8564-64198c3af088.png)

[logo_v4.pdf](https://github.com/popgensims/manuscript/files/3839378/logo_v4.pdf)

**Comment by petrelharp** [comment]
rough, and too big, but you get the idea?

**Comment by jradrion** [comment]
Nice! I like it!

**Comment by jeromekelleher** [comment]
These are all awesome!

One thing to think about is that it's really useful if a logo works in a square format. For example, if we want to use it as our GitHub avatar, it needs to look like something in a 40x40 pixel format.

**Comment by jradrion** [comment]
Here are a couple of squarish mock-ups...
![logo_v5](https://user-images.githubusercontent.com/20053488/69177543-92213280-0abc-11ea-87d6-b28fb829ffbe.png)
![laptop](https://user-images.githubusercontent.com/20053488/69177546-94838c80-0abc-11ea-9474-3a62f5c02c9d.png)

**Comment by andrewkern** [comment]
closing this as we now have a logo. Gracias @jradrion!
