### ISSUE TITLE
Get "standard library" into title?

### ISSUE THREAD

**Issue by jeromekelleher** [popgensims/manuscript#40]
The current title "stdpopsim: a community toolkit for population genetic simulation" risks being interpreted as "Yet another simulator: yawn". I think we want to get across the "standard library" or "catalog of simulation" concept

How about 

- A standard library of population genetic simulations
- A catalog of population genetic simulations
- A community maintained catalog of population genetic simulations

**Comment by andrewkern** [comment]
>     * A standard library of population genetic simulations
> 
>     * A community maintained catalog of population genetic simulations

I prefer these two. What if we recombine them to:

     * A community maintained standard library of population genetic simulations

**Comment by jeromekelleher** [comment]
I like it.

**Comment by petrelharp** [comment]
In the call just now, we have decided:

> A community-maintained library of population genetic models

**Comment by jeromekelleher** [comment]
Done.
