### ISSUE TITLE
migration rate plots

### ISSUE THREAD

**Issue by ckyriazis** [popgensims/manuscript#49]
should we add plots of the inferred migration rates for the two population inference to the supplement? i currently have these (somewhat ugly) plots that are automatically generated by the pipeline. i can add them to the figure repo if wanted.
![estimates_mig_dadi_fsc](https://user-images.githubusercontent.com/11757173/71024415-ba9b4d00-20b9-11ea-9ab8-30f6557ad66d.png)
![dromel_estimates_mig_dadi_fsc](https://user-images.githubusercontent.com/11757173/71024423-c129c480-20b9-11ea-86be-f507e3ba95fb.png)

**Comment by andrewkern** [comment]
sure these can go in the supplement. Can you simply turn these in to box and whisker plots?

**Comment by ckyriazis** [comment]
sounds good. i could either do box and whiskers or subset down to three inference replicates as we do for the pop size results? this is already the case for the human results here (top)...I think it could be a bit misleading to do box and whiskers with just three data points.

**Comment by andrewkern** [comment]
yeah huh... maybe we leave it as is.

**Comment by ckyriazis** [comment]
ill subset the drosophila one down to three data points and make them look a bit prettier then call it a day

**Comment by ckyriazis** [comment]
PR #59 closes this
