### ISSUE TITLE
model misspecification discussion

### ISSUE THREAD

**Issue by ckyriazis** [popgensims/manuscript#50]
one area where we can take the 'both sides' approach with the two pop results is to talk more about the issue of model misspecification. specifically, the SFS-based methods are limited by assuming some arbitrary number of epochs, whereas for smcpp, it is limited in assuming no migration. 

the human results are nice here because the true model includes migration (which is ignored by smcpp) but also exponential growth (which is more or less ignored by our SFS approaches). i think this would be a great case to point out strengths/weaknesses of these different approaches in the discussion.

**Comment by andrewkern** [comment]
yes I agree- want to take a stab at adding a sentence or two?

**Comment by ckyriazis** [comment]
sure ill try to get to this tomorrow.

**Comment by ckyriazis** [comment]
added this with #75
