### ISSUE TITLE
benchmark sims

### ISSUE THREAD

**Issue by agladstein** [popgensims/manuscript#6]
Has there been any talk of including a table/figure of expected run time and memory usage for the simulations?
I think as a user it would be helpful to have a table/figure to refer to have a general expectation of how long / how much memory the simulations will take. 
I'm not sure if this would be better in the supplemental or in the docs.

**Comment by jeromekelleher** [comment]
What do you think of the basic benchmarks in #14 @agladstein?

**Comment by agladstein** [comment]
I think those are good. 
Probably would be useful to run each of those 100 times and show the mean/median + std

**Comment by jeromekelleher** [comment]
> Probably would be useful to run each of those 100 times and show the mean/median + std

Ack, this is a bit pointless, isn't it? We're not doing science here, just giving people an indication of roughly how long they can expect sims to take.

**Comment by agladstein** [comment]
Maybe. Even though they are set parameter values, the run times are variable. e.g. I ran `stdpopsim homsap -c chr22 -o afr-america-chr1.trees -g HapmapII_GRCh37 --model america 4 4 4 4` and it took 32s, which is 3x what you have in the table (and I'm not using the same sample sizes you did). so, having an average would give people a better idea. But, I don't fee strongly about it.

**Comment by jeromekelleher** [comment]
You're using a different computer though...

**Comment by jeromekelleher** [comment]
The runs will vary a bit between replicates, but not usually that much. If we're not plotting the values I don't see much point --- we won't notice any difference between the mean and any particular value.

**Comment by andrewkern** [comment]
closing this as I think we settled on a solution
