### ISSUE TITLE
Popsim version ID

### ISSUE THREAD

**Issue by sgravel** [popgensims/manuscript#60]
https://github.com/popsim-consortium/manuscript/blob/6aca30af70e6265ed6f19129c0172c07226d1223/popSimManu.tex#L341
Will popsim have version id to facilitate reproducibility? If so, we could include this here since users may simply go through this section to decide what to report about their simulation. 

Else maybe somewhere else in the paper be explicit what data is needed to reproduce an analysis. (i.e., software versions, seeds, etc?)

**Comment by jeromekelleher** [comment]
Stdpopsim will have released versions, certainly. We should definitely encourage users to state the version they used, as parameters will vary between releases.

**Comment by sgravel** [comment]
Resolved by PR #73
