### ISSUE TITLE
Method citation cleanup?

### ISSUE THREAD

**Issue by sgravel** [popgensims/manuscript#61]
https://github.com/popsim-consortium/manuscript/blob/6aca30af70e6265ed6f19129c0172c07226d1223/popSimManu.tex#L77

This is a long citation list. It may be useful for readers if we cited the methods next to the specific or main task (inferring recombination, selection, or demography). It would perhaps also make sense to include here methods cited later in the paper (dadi [gutenkunst2009inferring], fastsimcoal [excoffier2013robust], and moments-LD [ragsdale2019models]). I would certainly cite dadi here since it is a household name at this point.

**Comment by jeromekelleher** [comment]
Agreed -- better to split up the citations.

**Comment by sgravel** [comment]
I cleaned this up and submitted a pull request. We could add a couple references to the DFE inference. (e.g. Ortega-Del Vecchyo https://www.biorxiv.org/content/10.1101/770966v1.abstract or Boyko et al. https://journals.plos.org/plosgenetics/article?id=10.1371/journal.pgen.1000083). I feel like @klohmueller might be the best to provide optimal list here.

**Comment by dortegadelv** [comment]
I wouldn't mind a citation :) Apart from those two references, I would also suggest Fortier et al ( https://www.biorxiv.org/content/10.1101/703918v1 ) and Huang and Siepel ( https://genome.cshlp.org/content/early/2019/06/27/gr.245522.118.full.pdf ). I will make a pass through the manuscript, will add these references and some other suggestions on a new PR.

**Comment by andrewkern** [comment]
closing as these PRs have been merged
