### ISSUE TITLE
PonPyg in documentation?

### ISSUE THREAD

**Issue by andrewkern** [popgensims/manuscript#63]
Seems like with https://github.com/popsim-consortium/stdpopsim/pull/338 we are now ready to include PonPyg in the documentation? 

@dschride and I were talking about whether or not to include it in the manuscript over here https://github.com/popsim-consortium/manuscript/pull/62#discussion_r359155370

**Comment by apragsdale** [comment]
I think at this point the basics of the species are there and can be simulated like any other species, so I don't see why not to include it. The only thing missing at the point is the rec map (see [this issue](https://github.com/popsim-consortium/stdpopsim/issues/342)). I have two orangutan recombination maps that were shared with me, but am not sure about including them in the resources we publish.

**Comment by andrewkern** [comment]
okay all set!
