### ISSUE TITLE
"usual factor-of-two" 

### ISSUE THREAD

**Issue by sgravel** [popgensims/manuscript#66]
I don't know what this refers to. Haploid vs diploid population sizes? If so, would we not have taken this into account?  It would be good to clarify or provide a citation in either case--there are too many "usual factors-of-two" in popgen.

**Comment by asiepel** [comment]
I think this is obviated by the edits Dan and I made to the Discussion yesterday, unless it also occurs somewhere else

**Comment by andrewkern** [comment]
agreed. closing.
