### ISSUE TITLE
PR/commit mixup

### ISSUE THREAD

**Issue by jradrion** [popgensims/manuscript#69]
@jeromekelleher, @andrewkern and I were wondering what might have happened here? How did my commit get included in @sgravel's PR?

What I found strange is that under my commit is says, "jradrion authored and sgravel commited". Any ideas? It's not really important, we're just curious.

<img width="1050" alt="Screen Shot 2019-12-18 at 10 22 42 AM" src="https://user-images.githubusercontent.com/20053488/71112799-285e7c00-2181-11ea-9389-708333885c5d.png">

**Comment by jradrion** [comment]
Maybe either @sgravel or I squashed the other's commit during a rebase?

**Comment by jeromekelleher** [comment]
Huh, that's weird. I haven't been watching the git history. Looks like one of you split off the wrong branch or did something odd when rebasing. The network looks fine though: https://github.com/popsim-consortium/manuscript/network

Looks like Adam, Chris and Kirk don't believe in feature branches though!

**Comment by sgravel** [comment]
Probably my mistake -- it's my first time rebasing and submitting PRs. I was editing my local master branch on my first PR, and presumably I rebased with your commit included. Apologies. 
I now create feature branches.

**Comment by jeromekelleher** [comment]
No harm done I'd say; feature branches FTW!

**Comment by jradrion** [comment]
`No harm done I'd say; feature branches FTW!`
Absolutely! Thanks all!

**Comment by ckyriazis** [comment]
@jeromekelleher not a matter of belief but rather github ignorance! i've been working off branches from my master in my fork and syncing the master as upstream updates occur. is there a better way to be doing this?

**Comment by jeromekelleher** [comment]
This [recommended workflow](https://stdpopsim.readthedocs.io/en/latest/development.html#github-workflow) will change your life @ckyriazis !

**Comment by ckyriazis** [comment]
wow!! this is a total game changer. thanks @jeromekelleher
