### ISSUE TITLE
Two population figures

### ISSUE THREAD

**Issue by ckyriazis** [popgensims/manuscript#7]
Opening an issue for further discussion about the two population figures and to share them with people that werent on the call. 
[two_pop_figures.pdf](https://github.com/popgensims/manuscript/files/3865726/two_pop_figures.pdf)

I made a few changes from the figures I showed this morning, including:
- fixed the issue with the Drosophila dadi results (I realized I used the wrong mutation rate for plotting - thanks for catching that Ryan)
- added cartoons of the true/fitted demographic models (looking for feedback on these)
- put a box around the divergence times to try to make them stand out more. alternatively, I could make an entirely separate panel at the top left of each plot, but I think it might be nice to keep them on the same x axis as the N trajectories even if the arbitrary y-axis is confusing. what do others think here?

Other points of discussion:
- should we include just one of these figures in the main text or both? if one, which one?
- we decided it makes more sense to show census size as the 'truth' here since we're modeling (at least some of the) migration. will it be confusing to have census size here vs the coal rate estimate for the n_t figure?

**Comment by RyanGutenkunst** [comment]
Nice quick fixes. A few thoughts...
1) The cartoons look good overall, but I don't like the glaring yellow. I would also label the end populations in the simpler models, like was done for the Human A panel.
2) I'm not sure we need all the parameter names called out in the simulated models. I guess we'll need them for reporting our simulated values. But they aren't really necessary for interpreting the results, and it would clean up the figure visually to omit them.
3) I like the divergence time box. I might also just add lettering next to them saying "divergence times" in the first panel where they're shown.

**Comment by ckyriazis** [comment]
Thanks @RyanGutenkunst ! I'll work up a new version based on these comments.

**Comment by ckyriazis** [comment]
Here are some updated versions. 

![homsap_twopop](https://user-images.githubusercontent.com/11757173/69364209-c7f22280-0c46-11ea-9ead-0686fc44f341.png)
![dromel_twopop](https://user-images.githubusercontent.com/11757173/69364223-caed1300-0c46-11ea-8321-7d377fe91b2e.png)

**Comment by RyanGutenkunst** [comment]
I like 'em! Thoughts, others?

**Comment by andrewkern** [comment]
sorry for the dumb question: what are the t_div dots in the subpanel?

In the meanwhile I'm going to include these as placeholders in https://github.com/popgensims/manuscript/pull/8

**Comment by ckyriazis** [comment]
the t_div dots are the true (black - see figures A and B) and inferred (blue) divergence times. i'm worried they might be confusing because their y axis values are arbitrary, but i thought it might be informative to see them on the same x axis as the n_t trajectories. if that is too confusing, i can plot them in a separate panel.

one other thing of note @andrewkern  - the true n_t trajectories here is the census size rather than inverse coalescence rate, which we decided on the call last week makes more sense in this context where we are modeling at least some of the migration (i noticed in the ms figure legend it says otherwise). we can revisit this conversation on the call today if need be.

**Comment by ckyriazis** [comment]
Here are the updated figures. Let me know if there are any further comments. 

![dromel_listephan](https://user-images.githubusercontent.com/11757173/70079548-d0891800-15b9-11ea-9937-4b7ffba1e172.png)
![homsap_gutenkunst](https://user-images.githubusercontent.com/11757173/70079550-d0891800-15b9-11ea-8af6-1f0862dcb6a7.png)

**Comment by andrewkern** [comment]
these look great. can you please submit them in a PR to the manuscript repo?

**Comment by ckyriazis** [comment]
Done.

**Comment by ckyriazis** [comment]
closing this
