### ISSUE TITLE
Acknowledgement Section

### ISSUE THREAD

**Issue by andrewkern** [popgensims/manuscript#84]
I've created an Acknowledgement section with this PR https://github.com/popsim-consortium/manuscript/pull/83#issue-354959547 (now merged)

Please add your own information if you feel comfortable with that or if not add it to this issue below. 

thanks

**Comment by petrelharp** [comment]
Anyone to add to this bit?
> Early on in the project we were helped by many people including XXXXXX.
Maybe we can delete this?

**Comment by andrewkern** [comment]
I was thinking we could acknowledge Patrick Phillips there.

**Comment by petrelharp** [comment]
Perhaps Richard Durbin.

**Comment by petrelharp** [comment]
For 'encouragement'?

**Comment by andrewkern** [comment]
👍

**Comment by asiepel** [comment]
I’d (humbly) suggest acknowledging the Simons Center for Quantitative Biology at Cold Spring Harbor Laboratory, which sponsored and paid for the first workshop.

On Dec 20, 2019, at 10:23 AM, Andrew Kern <notifications@github.com<mailto:notifications@github.com>> wrote:


👍

**Comment by andrewkern** [comment]
indeed. and who sponsored and paid for our latest meeting at ProbGen?

**Comment by asiepel** [comment]
not sure if there were any central funds for that one….. Jerome?

On Dec 20, 2019, at 10:26 AM, Andrew Kern <notifications@github.com<mailto:notifications@github.com>> wrote:


indeed. and who sponsored and paid for our latest meeting at ProbGen?

**Comment by philippmesser** [comment]
Wasn't Dmitri somehow involved in the initial conception of this idea? I know he didn't even come to the first meeting in CSH last year and don't think he participate in anything afterwards, but maybe it's still worth a mention in the acknowledgment section? Just throwing this out here and hopefully some of the others involved in the initial conception can comment.

**Comment by asiepel** [comment]
yes, I think “encouragement” would also be appropriate for Dmitri.  He was very enthusiastic at first and helped set the agenda for the first workshop but then seemed to get busy with other things.

On Dec 20, 2019, at 10:36 AM, philippmesser <notifications@github.com<mailto:notifications@github.com>> wrote:


Wasn't Dmitri somehow involved in the initial conception of this idea? I know he didn't even come to the first meeting in CSH last year and don't think he participate in anything afterwards, but maybe it's still worth a mention in the acknowledgment section? Just throwing this out here and hopefully some of the others involved in the initial conception can comment.

**Comment by petrelharp** [comment]
Adding these over in #127.

**Comment by andrewkern** [comment]
closing this down.
