### ISSUE TITLE
pongo sp inconsistencies

### ISSUE THREAD

**Issue by ckyriazis** [popgensims/manuscript#92]
very minor thing I noticed while reading through the ms just now...we are inconsistent in how we refer to Pongo (pygmaeus vs abelii), both in the text as well as Table 1 and Fig 1. its a two species model for both species, but I think we should pick one and stick with it.

**Comment by andrewkern** [comment]
i did a little digging here-- turns out this isn't a minor thing. the genome assembly we are using is for Pongo abelii not pygmaeus! what should we do here guys? @petrelharp @jeromekelleher

**Comment by jeromekelleher** [comment]
Huh, I wondered about that. I vote we file a bug on stdpopsim and move on. We're never going to get the data in the catalog perfect.

**Comment by andrewkern** [comment]
okay i'll follow your lead on this- how do we file a bug?

**Comment by ckyriazis** [comment]
so should we refer to P. pygmaeus in the ms then? if so we'll also have to get @jradrion to update figure 1

**Comment by andrewkern** [comment]
yes @jeromekelleher can table 1 be switched to P. abelii?

**Comment by jeromekelleher** [comment]
Just open an issue in stdpopsim describing the problem. We have to stick with PonPyg now, that's the name we've given it in the release. It's a bug that it's got the wrong genome information.

**Comment by ckyriazis** [comment]
closing this since its been resolved as far as the ms goes
