### ISSUE TITLE
models inconsistent with catalog

### ISSUE THREAD

**Issue by agladstein** [popgensims/manuscript#95]
Looks like models described in the text are inconsistent with what is currently in the catalog. Need to update.
- more human models in catalog
- more A. thaliana models in catalog
- none for E. coli
- one for Pongo

**Comment by jeromekelleher** [comment]
So there's stuff in the table that we're not talking about in the text?

**Comment by agladstein** [comment]
Yes

**Comment by agladstein** [comment]
from 
https://github.com/popsim-consortium/manuscript/blob/master/popSimManu.tex#L331
to
https://github.com/popsim-consortium/manuscript/blob/master/popSimManu.tex#L354

**Comment by agladstein** [comment]
this is closed by https://github.com/popsim-consortium/manuscript/pull/97
