### ISSUE TITLE
add diagram of workflow

### ISSUE THREAD

**Issue by agladstein** [popgensims/manuscript#96]
could we add a diagram of the analysis workflow to the supplemental?

**Comment by jeromekelleher** [comment]
Sure, if someone would like to make it...

**Comment by agladstein** [comment]
Unless one of the original analysis people who wrote the workflow want to make it, I can draw it. If I do it, could be a good test if explanation actually is clear.

**Comment by ckyriazis** [comment]
I'm happy to help and provide feedback.

**Comment by petrelharp** [comment]
This is a good idea, but since we haven't done it, I propose we push this off until resubmission.

**Comment by andrewkern** [comment]
yeah seems right to me.

**Comment by agladstein** [comment]
When are you planning to submit? Because I can get up a draft diagram within an hr or two. Or I can just wait.

**Comment by petrelharp** [comment]
"today"? @andrewkern ?

**Comment by andrewkern** [comment]
don't think we need it
