### ISSUE TITLE
manuscript title

### ISSUE THREAD

**Issue by asiepel** [popgensims/manuscript#98]
Perhaps I missed something, but I thought we had discussed changing the language in the title away from "library of simulations" to something more like "library of models", which I think captures better what we're providing here.  "Library of simulations" sounds to me a bit like a collection of pre-generated simulated data sets.

**Comment by andrewkern** [comment]
yeah i noticed that too. i will edit to library of models as we agreed upon.

**Comment by andrewkern** [comment]
this will be closed by https://github.com/popsim-consortium/manuscript/pull/111

**Comment by petrelharp** [comment]
... which was merged.
